### ISSUE TITLE
Issue starting up

### ISSUE THREAD

**Issue by ttback** [zemanel/openshift-diy-django-example#1]
So I tried your repo with following 
rhc app create diydjango diy-0.1
cd diydjango
git remote add diy -m master https://github.com/zemanel/openshift-diy-django-example.git
git pull -s recursive -X theirs diy master
git push

Then when i try to access it from browser, it says Service Temporarily Unavailable.

Any extra I need to do to make it work?

**Comment by zemanel** [comment]
maybe the repo example source is outdated. Will test and update if
required, between today and tomorrow !
 No dia 22 de Mar de 2013 15:11, "[T]" notifications@github.com escreveu:

**Comment by zemanel** [comment]
in the mean time, if you can attach any debug info like the rhc CLI log output for the instance, it would be helpful.

I will also update the example for Django 1.5

**Comment by ttback** [comment]
you mean the git push logs or?

**Comment by ttback** [comment]
ultimately i am trying to see if I can get gunicorn + nginx working with django. Havent had that working yet.

**Comment by zemanel** [comment]
if possible or the rhc cli has log tailing commands.

will only be able to take a look at it tomorrow, first thing in the day ;)

gtalk: zemanel@zemanel.eu
skype: zemanel_eu
No dia 22 de Mar de 2013 21:19, "[T]" notifications@github.com escreveu:

**Comment by ttback** [comment]
When i run ctl_all restart

Stopping services...
/.openshift/action_hooks/stop: line 7: kill: (10874) - No such process
Failed to stop diy-0.1
Starting services
app-root/runtime/repo/petstore/settings.py:190: UserWarning: Failed to import petstore.local_settings
 warnings.warn("Failed to import %s" % dottedpath) # <-- will show up in your error log
app-root/runtime/repo/petstore/settings.py:190: UserWarning: Failed to import petstore.deploy.settings.pydiy
warnings.warn("Failed to import %s" % dottedpath) # <-- will show up in your error log
Done

pydiy = app name

**Comment by zemanel** [comment]
seems like an error on the pydiy.py module, which is not being imported.

I'll check it out, thanks !

gtalk: zemanel@zemanel.eu
skype: zemanel_eu
No dia 22 de Mar de 2013 23:56, "[T]" notifications@github.com escreveu:

**Comment by zemanel** [comment]
im updating the project, simplifying the config, updating the requirements to latest Django 1.x branch and removing task queue stuff (lack of shared mem support last i knew) and will update the README properly. Will poke you when it's done.

**Comment by ttback** [comment]
Thanks. Wow, your responsiveness is incredible! I didn't expect this since it is nothing super urgent, but thanks for helping. I am still very new to both django and openshift but I can't wait to see what you changed to make it work again.

**Comment by zemanel** [comment]
no problem i love to help, also it's a very simple thing. unfortunately had
a busy day and only managed to get to  my laptop for 10m to check things
out.

Also there are other and maybe better examples on the openshift account
repos at the moment.

Feel free to add my contacts to gtalk etc and i'll gladly boost you onwhat
i know :)

gtalk: zemanel@zemanel.eu
skype: zemanel_eu
No dia 23 de Mar de 2013 19:54, "[T]" notifications@github.com escreveu:

**Comment by ttback** [comment]
added your gtalk

**Comment by hsingh23** [comment]
ttback - did you get nginx and gunicorn working?

**Comment by ttback** [comment]
not yet... I did get nginx working easily. Then I ran out of time to play with gunicorn. It doesn't look too bad. 
Here's a guide http://senko.net/en/django-nginx-gunicorn/
I learned that the reason why I couldn't get everything working was because I started out with a python2.6 cartridge. It has to be DIY if i want to mess around with httpd to make nginx work with gunicorn.

**Comment by zemanel** [comment]
picking this issue now.

In regard of using Nginx as a frontend, it may be possible even of automating the compilation out of the box. My question at the moment is if it is necessary, meaning, if the app's exposed directly to the web on $OPENSHIFT_INTERNAL_IP:$OPENSHIFT_INTERNAL_PORT or Openshift has a frontend router / proxy itself (not sure at the moment).

**Comment by zemanel** [comment]
i've refactored and improved much of the sample project, which is currently sitting on a branch:

https://github.com/zemanel/openshift-diy-django-example/tree/feature/django-1.4.5-update

please take a look at the commit logs and let me know if it makes sense to you and shoot any questions, because some changes may break existing projects based on this setup.

**Comment by zemanel** [comment]
tested and merged the branch into master.

**Comment by zemanel** [comment]
closing issue as this does not apply anymore
