### ISSUE TITLE
Static assets

### ISSUE THREAD

**Issue by equinoxel** [zemanel/openshift-diy-django-example#4]
The original django example on openshift does some processing with a .htaccess from the wsgi/static directory. Your example serves assets via django. Is there a way to replicate the openshift functionality and not serve static files from django?

TIA,

**Comment by zemanel** [comment]
Hi, i will take a look. I had configured static files to make use of that but it seems something's missing.

**Comment by equinoxel** [comment]
Cheers!

**Comment by zemanel** [comment]
As far as i know, DIY cartridges do not support direct static file serving and i believe i added the file collection with the intention of either plugging in Nginx or something else in the future.

Closing issue (for now)
